
apiVersion: apps/v1
kind: Deployment
metadata:
 name: testd-deployment
 labels:
   app: test
spec:
 replicas: 10
 selector:
   matchLabels:
     app: test
 template:
   metadata:
     labels:
       app: test
   spec:
     containers:
     - name: httpd
       image: httpd:alpine3.18
       command: ["/bin/bash", "-c"]
       args: ["sleep 5; exit 1"]
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1

